### ISSUE TITLE
Are you going to release a new version at all?

### ISSUE THREAD

**Issue by asterictnl-lvdw** [hemker/apkgrabber#100]
It has been a long time since a new version has been released. This version is more buggy than the one of rumboalla. Let me know if a new version will be released or if there is a fork.

**Comment by hemker** [comment]
Currently there is no plan to release new features, as rumboalla has updated the original version. Furthermore, with Aurora Store I don't see any use cases that are not covered by these two apps.

**Comment by mindtrapper** [comment]
Where is this new version? Latest I see is 2.0.5

**Comment by Elite911** [comment]
> Where is this new version? Latest I see is 2.0.5

I don't think there is a newer version. Last update is that one from 2021. 

Only thing hemker is referring to is updates to commits on GitHub but there's no actual update to the app released.

**Comment by hemker** [comment]
@DarkCrypt I've already received the news in ApkUpdater which is great! So I think it's better to join forces and maybe contribute by implementing new sources than keeping this kinda outdated stack running.

**Comment by DarkCrypt** [comment]
@hemker
I agree with you, joining forces is a much better idea! You already have experience with the project and would be a very valuable contributor. You could help rumboalla take ApkUpdater to a whole new level. I'm already excited about the return of ApkUpdater and I'd be even more excited if you decide to contribute. That'd be awesome!

**Comment by oroboros** [comment]
> Currently there is no plan to release new features, as rumboalla has updated the original version. Furthermore, with Aurora Store I don't see any use cases that are not covered by these two apps.

I'd invite you to reconsider! There's clearly a following that misses the app and that thinks whatever alternatives are lacking compared to your version!

**Comment by je-vv** [comment]
@hemker would you consider archiving this repo then?
