### ISSUE TITLE
Add Github / FDroid Repos source

### ISSUE THREAD

**Issue by Parstion** [hemker/apkgrabber#11]
It's possible to add ?

**Comment by MegaArthur** [comment]
For adding GitHub releases, IzzyOnFdroid's repo could be used - he uses Github releases in his repo

**Comment by TPS** [comment]
@hemker: @IzzySoft's repo shows different versions, but same build number ("29") for every released build.  I think that's confusing my F-Droid client.  Where does the fix need to be, in the APK or the repo?

**Comment by IzzySoft** [comment]
As those details get extracted from the APK, there's nothing I can do about that, @TPS – Uh-oh, @hemker: You must increase versionCode with each release!

    package: name='de.apkgrabber' versionCode='29' versionName='1.1.4' platformBuildVersionName='8.0.0'
    package: name='de.apkgrabber' versionCode='29' versionName='1.1.2' platformBuildVersionName='8.0.0'
    package: name='de.apkgrabber' versionCode='29' versionName='1.1.0' platformBuildVersionName='8.0.0

That's what Android (and also F-Droid) identifies a version. Users won't get any update information otherwise!

I just deleted all APKs here except for the latest, so that at least that shows up (and first-timers get the recent version). Please remember increasing versionCode with each new release from now on. Thanks!

**Comment by hemker** [comment]
@IzzySoft @TPS with version v1.1.7, the version code is incremented. Sorry for the inconvenience, was't aware about that

**Comment by IzzySoft** [comment]
Happens all the time (you're not the first, so no worries :rofl:). Important thing is to detect and fix it – and that we have now. Thanks, @hemker: 1.1.7 should be fetched in about an hour, and with that the issue should be solved.

**Comment by hemker** [comment]
Perfect, definitely have to setup CD as a short-term goal :D

**Comment by IzzySoft** [comment]
First let me confirm: the new package was grabbed and integrated successfully, so the problem reported by @TPS is solved.

As for a "REST API": not exactly. But it's an F-Droid repo, so the same "interfaces" exist – i.e. you could parse the index. Or check whether `https://apt.izzysoft.de/fdroid/index/apk/<package_name>` returns a 404 (app not there; if it's available, `//div.package[1]/h4[1]` has version information in its "nodeValue" – but that's only for my repo).

Easiest approach would probably be to grab the index files of all F-Droid Repos you think are interesting (see e.g. my [Unofficial (and incomplete) list of F-Droid repositories](https://android.izzysoft.de/catmin/articles/named/list-of-fdroid-repos) once per day and parse them on your server to feed some DB with the relevant details. There's e.g. [php-fdroid](https://gitlab.com/fdroid/php-fdroid) as PHP library to parse the XML index.

**Comment by TPS** [comment]
@IzzySoft The link to your list of F-Droid repos asks for authentication from "Privileged Users".…  Is that correct?

**Comment by IzzySoft** [comment]
No, that's not correct. My fault, copied from the from place and forgot to adjust. Try again, I've fixed it.

**Comment by jawz101** [comment]
How would you do this if there is signature mismatches?  I would think this is out of scope of this app.

**Comment by IzzySoft** [comment]
@jawz101 signature mismatches only happen between the F-Droid main repo and other sources – not with my repo and other sources (except for F-Droid main). I don't sign the apps myself, they have the original developers' signatures (as that's where I get the APKs from). F-Droid builds from source and signs with their key, so they have a different signature.
