### ISSUE TITLE
[FR] Add option how updates are downloaded

### ISSUE THREAD

**Issue by tjsuominen** [hemker/apkgrabber#13]
Add an option in App preferences how the actual update downloads are performed:

1) Either as 'old APKUpdater'; visit APKMirror or
2) Direct download (as by APKGrabber currently)

**Comment by tjsuominen** [comment]
Had been implemented already in 1.1.2, I was slow. Can be closed :)

**Comment by Niek** [comment]
Maybe I'm missing something, but I don't see the option to download directly from APKmirror in-app (it only links to the site)?
