### ISSUE TITLE
Play Store versions

### ISSUE THREAD

**Issue by quthla** [hemker/apkgrabber#16]
Since latest version it'll just show current installed version 2x instead of the question mark. What's the point in that?

Maybe the version issue is fixed if you update to latest deps like this https://github.com/rumboalla/apkupdater/pull/254

**Comment by hemker** [comment]
damn, that's right. I'll have a look at it.

**Comment by hemker** [comment]
upgrading the version does not fix the missing version name, added an issue to yeriomin repo. Maybe I can find out by myself with some time.

**Comment by hemker** [comment]
@quthla new release is out, please test again

**Comment by quthla** [comment]
Working good now 👍

**Comment by quthla** [comment]
I still get a crash though when the app was in background for some time. When I start the app again then, it'll not crash
