### ISSUE TITLE
beta versions from google play

### ISSUE THREAD

**Issue by patrickdrd** [hemker/apkgrabber#18]
it fetches beta versions from google play,
even though betas are set to be disabled in settings

e.g. pushbullet

**Comment by hemker** [comment]
Installed pushbullet 17.8.15 and I see 18.2.6 as proposed update. Does not seem to be a beta.

**Comment by patrickdrd** [comment]
it isn't now, but it was at the time I posted, anyway now I've got another problem, app crashes constantly

**Comment by hemker** [comment]
I need logs for investigating that, please dump via logcat

**Comment by patrickdrd** [comment]
I'm not root on this device so it's not easy

**Comment by hemker** [comment]
You don't need to be root, you just have to enable developer settings. Then you can use logcat. Follow any tutorial on Google for something like "android logcat show logs"

**Comment by patrickdrd** [comment]
yeah and I had to turn on computer etc, 
nevermind I preferred to uninstall the app,
thanks anyway

**Comment by hemker** [comment]
Sorry, that was not intended to sound ironic - didn't know anything about your general android skills. Nevertheless, I'm still interested to fix that crash issue, as it might concern multiple users/devices. Any steps to reproduce?

**Comment by patrickdrd** [comment]
don't worry, it didn't sound ironic and my android skills are pretty decent,
I was just too sleepy at the time and I went to sleep and in the morning I had 
a lot of things to do,
after all I didn't feel it was an important app for these (two) devices anyway,
I should be keeping for the third one though because that one I open just occasionally,
so it would be useful there in order to not forget to run an update

anyway, as for the steps, I've had same issue with apkupdater,
just before you took over, and I can't say I did anything particular with it 
in order to reproduce it,
while it was working one day the next it broke and it wouldn't open again,
my settings were all set to manual mode and I had kept apkmirror and google in servers to check

**Comment by jawz101** [comment]
The reason I use this app is _to_ find betas.  Are you trying to omit them?

**Comment by patrickdrd** [comment]
yes, I don't want them so I have excluded them from the relevant setting
