### ISSUE TITLE
Checking for updates while in on android P causes phone to vibrate wildly / set off a lot of notification alerts

### ISSUE THREAD

**Issue by pagzamaphone** [hemker/apkgrabber#25]
Running on Android P with March security updates on an Essential PH-1

It appears the priority for the notifications to update the count of the progress bar is set too high, which causes the phone to vibrate/alert once per every time the loading bar moves, so when its checking ~400 apks, it may do a lot. 

Coming from APKUpdator this is different, and i'm assuming unintended behaviour.

Let me know if more repro steps are needed.

**Comment by TPS** [comment]
This can be worked around by disabling vibration for just that notification (Android System Settings → Apps & Notifications → APKGrabber → App Notifications → {Pick whichever category} → Vibrate), while @hemker works on the fix.

**Comment by Kaz1993** [comment]
I think this line in the NotificationHelper is causing the issue 

`channel.setVibrationPattern(new long[]{100, 200, 300, 400, 500, 400, 300, 200, 400});`

Maybing adding "100" is good enough.

**Comment by hemker** [comment]
@pagzamaphone should be fixed in current release. Please confirm.

**Comment by pagzamaphone** [comment]
At first i didn't think it did resolved the issue, because all i did was upgrade from the previous version to this version, however after clearing my storage for the app it appears to have resolve the issue. 

I dunno if you need to clear the database or something between versions to make sure that new notification helper setting take effect, but it works now, so i'm finally going to switch over to using it and uninstall apkupdater :)

**Comment by hemker** [comment]
@pagzamaphone settings like notification channel vibration patterns are persistent between app versions, so after the pattern is fixed now, an unique cleaning of your app data (as you already did and explained) will fix the problem.
