### ISSUE TITLE
Ignored updates cannot be un-ignored

### ISSUE THREAD

**Issue by yochananmarqos** [hemker/apkgrabber#28]
When ignoring an app from the Installed tab, it shows grayed out at the bottom of the list and can be un-ignored. When ignoring an app from the Updates tab, it does not change in the Installed tab. Choosing ignore does nothing and there's no way to un-ignore it.

**Comment by pagzamaphone** [comment]
I can reproduce this issue. 

The workaround could be to completely clear the storage for the app but then you lose your settings, and this is a pretty easy bug for a user to hit, so should probably be fixed
