### ISSUE TITLE
Does not work on Fire TV devices

### ISSUE THREAD

**Issue by razfazz** [hemker/apkgrabber#29]
the android tv and especially fire tv market is huge and this app offers an outstanding added value. 
unfortunately the app does not support dpad navigation. please make this app compatible with non touch devices.

**Comment by hemker** [comment]
@smedasn haven't tested on a non-touch device for now, but Android should support dpad mapping out of the box. Is any kind of interaction possible so far?

**Comment by smedasn** [comment]
unfortunately it does not work very well on non touch devices. take a look at this video 

https://youtu.be/kvc7Tyhs3Tc

with dpad support it would work without virtual mouse which would be amazing.
