### ISSUE TITLE
Add Aptoide as an update source

### ISSUE THREAD

**Issue by TacoTheDank** [hemker/apkgrabber#32]
Title is self explanatory, I suppose.

**Comment by hirenshah** [comment]
This would be cool :-)

**Comment by hemker** [comment]
Will try to implement this in upcoming relase

**Comment by hemker** [comment]
@TacoTheDank @hirenshah Release is out!

**Comment by hirenshah** [comment]
Nice one! Downloading it now!

**Comment by hirenshah** [comment]
Google Drive was available an update via Aptoide. Clicking on it took me to a game called 8 Ball in the Aptoide app.

**Comment by hemker** [comment]
I think Aptoide app interrupts the execution of your browser because of a registered mapping for urls like *aptoide.com*. Is it the same with all updated from aptoide or just Google Drive? I checked the Google Drive JSON response from Aptoide and it's fine.

**Comment by hirenshah** [comment]
If I select the browser instead of the Aptoide app, nothing actually loads up in Chrome. Same applies for other updates that are available.

**Comment by hemker** [comment]
@hirenshah replaced the clicking of APTOIDE with a direct download, please check it in release 1.6.2. After the download is completed, installation is started

**Comment by hirenshah** [comment]
I didn't get a chance to check 1.6.2 but can confirm that it works with 1.6.3 👍🏽

**Comment by hemker** [comment]
Perfect, I close this one now!

**Comment by TacoTheDank** [comment]
Yay, thank you! :)
