### ISSUE TITLE
Download in progress

### ISSUE THREAD

**Issue by tjsuominen** [hemker/apkgrabber#4]
Indicate somehow in the UI (for the selected app) that download is in progress (otherwise there's no indication of something in progress...)

**Comment by hemker** [comment]
The download is initiated via the Android download manager, so you should see a little arrow in your status notification bar - at least I see that. Could you confirm that?

**Comment by TPS** [comment]
Given Android has many issues w/ its Download Manager (especially when a VPN is used), is there any hope for an alternative download method?

**Comment by tjsuominen** [comment]
Hi. If I remember correctly, I did not see the "downloading" arrow in my status bar. Neither I have a VPN in use. With the "old" APKUpdater, I did get that arrow. Let me double check when the next update(s) get notified -> I'll get back.

**Comment by hemker** [comment]
Hey,
due to removal of auto download feature (see XDA thread -> terms of service of APKMirror), this is currently not important anymore. I close this.

**Comment by TPS** [comment]
This download is also used when installing from Google Play, right?  So this still is a problem, @hemker.…
