### ISSUE TITLE
Scheduled checking stopped working (1.4.2)

### ISSUE THREAD

**Issue by tjsuominen** [hemker/apkgrabber#45]
With 1.4.2 APKGrabber no longer seems to perform scheduled update checks. I haven't changed any settings (Notifications: Always, Check for updates: Daily, Update hour: 20:00, Sources: APKMirror).

Manually launching the app works fine and updates are being checked upon launch - but NOT for the scheduled time on daily.

**Comment by tjsuominen** [comment]
Any chance @hemker ironing this issue out? :)

**Comment by hemker** [comment]
@tjsuominen yes, there is a chance :D I'm quite busy atm, but as soon as possible I begin fixing some stuff for APKGrabber!

**Comment by tjsuominen** [comment]
@hemker Brilliant, take your time! :) 👍

**Comment by tjsuominen** [comment]
Hi @hemker - hope everything is ok with you (yes, busyness and holidays happens sometimes :D). Any possibility to receive updates / fixes in the future?

**Comment by hemker** [comment]
@tjsuominen Hey, yes, everything is fine :D I am currently talking to a guy knowing some stuff better than me, especially timer scheduling on newer android APIs. I will head on to get this issue fixed in the next future.

**Comment by tjsuominen** [comment]
Great news and happy to hear all is fine! Looking forward to AG future updates :)

**Comment by hemker** [comment]
@tjsuominen Will complete the bugfix when I'm back home in the end oft the week, so probably a new version will be released next week.

**Comment by hemker** [comment]
@tjsuominen Should be fixed in current release, please confirm. Notice that there is no chance to get a precise scheduling, e.g. setting update hour to 12:00 can cause android greater than 7 to schedule the alarm at 12:01 or 12:02.

**Comment by tjsuominen** [comment]
@hemker I won't report an issue should that non-preciseness occur ;-) Shall do the update tonight and report back tomorrow how did go. Seems need to un-install current version first.

**Comment by hemker** [comment]
@tjsuominen Ping? :D

**Comment by tjsuominen** [comment]
Ping @hemker - check and validated as working - good job!

**Comment by hemker** [comment]
@tjsuominen thanks, feels good to tally this issue :D
