### ISSUE TITLE
notification sound bug

### ISSUE THREAD

**Issue by bingoxo** [hemker/apkgrabber#48]
when i search for updates , it keeps making the notification sound and there is no way to stop it ( have to wait for about 10 seconds)

**Comment by TPS** [comment]
Zombie #25, I fear.  [Workaround from that still works](https://github.com/hemker/apkgrabber/issues/25#issuecomment-475740522):
>This can be worked around by disabling vibration for just that notification (Android System Settings → Apps & Notifications → APKGrabber → App Notifications → {Pick whichever category} → Vibrate), while @hemker works on the fix.

**Comment by hemker** [comment]
@bingoxo Is this still present in a recent release?

**Comment by antkoul10** [comment]
I'm facing this on the latest version (Android P). Let me know if I can help somehow.

**Comment by hemker** [comment]
@antkoul10 should be fixed in current release. Could you confirm,

**Comment by antkoul10** [comment]
It is indeed fixed. Thank you!
