### ISSUE TITLE
Auto-refresh option

### ISSUE THREAD

**Issue by tjsuominen** [hemker/apkgrabber#5]
After installation completed /app > have option in the preferences to auto-refresh the "Updates (x) list?

**Comment by hemker** [comment]
@tjsuominen fixed in latest release

**Comment by hemker** [comment]
@tjsuominen added in latest release. please confirm so I can close this issue.

**Comment by hemker** [comment]
@tjsuominen ping? Want to be sure and close this isse :D

**Comment by Rool-IO** [comment]
If I may, this auto refresh would be more effective if only searching for the installed app, obviously using less data & resources.

**Comment by tjsuominen** [comment]
@hemker Yes I confirm and can be closed :)
