### ISSUE TITLE
Request: Could you add the XDA Labs Repository to the sources

### ISSUE THREAD

**Issue by mikhoul** [hemker/apkgrabber#53]
Could you add the [XDA Labs Repository](https://labs.xda-developers.com/) to the sources since there is some exclusives apps that are hosted only on XDA.

https://labs.xda-developers.com/

**Comment by tjsuominen** [comment]
Just curious, how would adding this to benefit instead of using XDA own app (includes also browsing the discussions etc.)?

**Comment by mikhoul** [comment]
I prefer to use just one app instead of using many apps to make all my updates.
