### ISSUE TITLE
Request to have a download manger to be integrated to  transparently download and install the APK from the various sources without the need to use a browser

### ISSUE THREAD

**Issue by mikhoul** [hemker/apkgrabber#56]
The request is to have a download manager that would transparently download and install the APK from the various sources without the need to use a browser .

Regards :octocat:

**Comment by tjsuominen** [comment]
At least for APKMirror this is not gonna happen (due to agreed "policy" with APKMirror). Was implemented earlier, removed by request.

**Comment by mikhoul** [comment]
Thanks a lot for the tips  I will make a personal build till it change  :wink:  .

**Comment by hemker** [comment]
Will not be implemented generally, only for source specific.
