### ISSUE TITLE
Cant add own Google account

### ISSUE THREAD

**Issue by AAlchemy** [hemker/apkgrabber#58]
When launching Firefox to get the 2FA token, the oauth2 results never handoff to APKGrabber. The whole process just stops at the browser (One moment please...). I did reinstall Chrome for a test point and the last step of the oauth2 process chrome send a web intent but apkgrabber is not one of the options in the popup.

**Comment by tjsuominen** [comment]
#meetoo

**Comment by pagzamaphone** [comment]
confirmed this is still a bug in case anyone recently hit it.
