### ISSUE TITLE
[FR] Backup settings and Applist

### ISSUE THREAD

**Issue by tjsuominen** [hemker/apkgrabber#59]
Minor priority, but could be useful in some "crash" / uninstall cases: ability to backup & restore APGrabber settings and app list (check/not-to-check) statuses to Google (tied to your Android account?).

**Comment by keatonthewise** [comment]
This is a great idea! I second this notion.

**Comment by tjsuominen** [comment]
Hi @hemker, any possibility for implementing this one? :)

**Comment by patrickdrd** [comment]
+1
