### ISSUE TITLE
Restore APK Mirror page link

### ISSUE THREAD

**Issue by yochananmarqos** [hemker/apkgrabber#6]
From my post on [XDA](https://forum.xda-developers.com/showpost.php?p=79030951&postcount=508): I actually preferred tapping the APKMIRROR button to go to the page. Most of the time the wrong version appears in the app, so I have to go to the page to download the right one. Could you add the option for both?

**Comment by TPS** [comment]
@hemker A bit related: tapping that link currently downloads something that doesn't end in .apk .…  Assuming that's the APK, could that be added?

**Comment by hemker** [comment]
will be fixed/added in next release
