### ISSUE TITLE
How does one install this?

### ISSUE THREAD

**Issue by qazip** [hemker/apkgrabber#63]
Both aurora store and yalp store are not working for me so I came across this software. How does one install apkgrabber so I can install an app from google-play?

**Comment by tjsuominen** [comment]
APKGrabber is for *updates*, it ain't no Play Store / any store replacement.

**Comment by deerp** [comment]
There's a new fork for yalp in fdroid. You can download directly from here -https://f-droid.org/en/packages/com.github.kiliakin.yalpstore/

The issues I had such as not being able to view apps from same developer as an app I've got downloaded have been fixed. Seems much more stable than the original yalp.
