### ISSUE TITLE
Check for version

### ISSUE THREAD

**Issue by ChristophHeilmann** [hemker/apkgrabber#64]
I suppose APKGrabber checks for package name and date. But somtimes that's not enough. 
The ARTE app (https://www.apkmirror.com/apk/arte/arte/arte-5-17-1-release/arte-5-17-1-android-apk-download/download/) and the ARTE TV app (https://www.apkmirror.com/apk/arte/arte-android-tv-2/arte-android-tv-2-1-0-1-release/arte-android-tv-1-0-1-android-apk-download/) have the same package name and signature but when you look in the manifest file they are actually different. 

![Screenshot](https://user-images.githubusercontent.com/9595209/64132817-abc2b000-cdd2-11e9-9e20-215f2d96375f.png)

**Comment by deerp** [comment]
I'm having a similar issue. ApkGrabber is finding new update for Windscribe on APKMirror but when I check it's the Android TV version.

![Screenshot_20190910-032336](https://user-images.githubusercontent.com/52018316/64579475-f87e2c00-d37a-11e9-8534-15b8984ac824.png)
![Screenshot_20190910-032127](https://user-images.githubusercontent.com/52018316/64579476-f916c280-d37a-11e9-8330-dfdca6222d68.png)
