### ISSUE TITLE
Aptoide and Substratum Error

### ISSUE THREAD

**Issue by hirenshah** [hemker/apkgrabber#67]
Scanning for updates with Aptoide selected always errors with this message:
![SmartSelect_20191106-142246_APKGrabber](https://user-images.githubusercontent.com/418112/68306279-29d85700-00a1-11ea-8c5b-1f3b500e00cd.jpg)

If I ignore that app, there are no errors 🙂

**Comment by tjsuominen** [comment]
With Aptoide it finds and downloads new updates yes, but I get the "App not installed" error all the time. What could be causing that? @hemker any glue on this?
