### ISSUE TITLE
Error 401: Unauthorized when downloading from Google Play

### ISSUE THREAD

**Issue by EmberHeartshine** [hemker/apkgrabber#73]
Title. I am unable to download from Google Play using the shared token, and the "Use own Google Account" option does not work ("There was an error attempting to get the token", even when I use the correct app password).

**Comment by realkot** [comment]
Same issue too

**Comment by alcusto** [comment]
Same for me. When I click on "Install" for Play Store updates, I get error 401. Please solve. This was the only way I had to update those apps which have Country block in my Country

**Comment by TPS** [comment]
Have you tried using [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore)?  If you use [F-Droid](https://f-droid.org/), you may prefer grabbing a build from https://f-droid.org/en/packages/com.aurora.store/ or else from https://gitlab.com/AuroraOSS/AuroraStore/-/releases.
