### ISSUE TITLE
Build Number Comparison Update

### ISSUE THREAD

**Issue by hirenshah** [hemker/apkgrabber#77]
Just installed the latest version and immediately noticed an issue. Previously only one entry appeared for this app. 

![Screenshot_20201120-151856_APKGrabber](https://user-images.githubusercontent.com/418112/99816680-e766a880-2b43-11eb-8088-3fca49b2e961.jpg)

**Comment by hirenshah** [comment]
Definitely something wrong with the update. I used to get separate Aptoid and APKMirror entries for Instagram but now it's worse.

![Screenshot_20201120-180540_APKGrabber](https://user-images.githubusercontent.com/418112/99834231-2b18dc80-2b5b-11eb-803f-bf40999d789d.jpg)

**Comment by hemker** [comment]
A bite more information would be useful. What Android are you using? Does it affect all apps, or only a few? Only on certain positions in the view?

**Comment by hemker** [comment]
@hirenshah Should be fixed in current release, please confirm.

**Comment by hirenshah** [comment]
> @hirenshah Should be fixed in current release, please confirm.

Looking Good :-)

**Comment by hemker** [comment]
@hirenshah Alright, I close this now :) Thanks.
