### ISSUE TITLE
[Bug] Target update version doesn't appear when DLing from Google Play

### ISSUE THREAD

**Issue by MegaArthur** [hemker/apkgrabber#8]
As in the title, when an update's found on Google Play through ApkGrabber, the updated version is a "?", although the target version code is still displayed correctly.

**Comment by hemker** [comment]
should be fixed in latest release, please confirm

**Comment by MegaArthur** [comment]
Now, with the latest release it's not a question mark, but the exact same version as the current one.

**Comment by hemker** [comment]
@MegaArthur new release is out, please check if it is fixed

**Comment by MegaArthur** [comment]
Yes, it's good now, thanks!
