### ISSUE TITLE
All the sources you should add (there are some you already have) 

### ISSUE THREAD

**Issue by EngineerGlitch** [hemker/apkgrabber#85]
@hemker 
- Aptoide (Less important) 
- F-Droid
- Apk Mirror
- Google Play (Less important) 
- Github/Gitlab repository
Delete Uptodown (contain adwares), and I'm thinking about APKPure.

**Comment by GlitchGuy01** [comment]
But thank you for forking APK Updater and improving it.

**Comment by D19A66B55** [comment]
Thanks for a great app and your hard work.
If you wouldn't mind, I'd like to request an addition which is to add APKCombo.com to your app.
This site is very useful and has good ratings.
Happy Holidays😊

**Comment by ifelixculpa** [comment]
anyupdate on these ?
