### ISSUE TITLE
App crashes at launch

### ISSUE THREAD

**Issue by Cyberavater** [hemker/apkgrabber#88]
Crash log: https://del.dog/idoppocyck

**Comment by PCUser2021** [comment]
Same issue at every launch, samsung j700f android 6.0.1

**Comment by PCUser2021** [comment]
> Crash log: https://del.dog/idoppocyck

How did you created the log file?

**Comment by Cyberavater** [comment]
> Crash log: https://del.dog/idoppocyck

How did you create the log file?

You can use a Logcat app. For me, it's a feature of the Rom I'm using. Every time an app crashes, my device suggests me to send this link to the app's dev. BTW, I'm using BlissRom.

**Comment by Cyberavater** [comment]
A possible workaround for this issue is to clear app data.

**Comment by PCUser2021** [comment]
> A possible workaround for this issue is to clear app data.

Still crashes no matter what I do!
Please fix this bug ASAP.

**Comment by PCUser2021** [comment]
Someone please help, I can't download even open the app!

**Comment by Cyberavater** [comment]
Just don't use this app, it's not that important to have, use Aurora store
if It can help.
