### ISSUE TITLE
Press Ignore to much will force Quit It

### ISSUE THREAD

**Issue by psyscope** [hemker/apkgrabber#9]
Pressing ignore a couple times can lead the app to force quit.

**Comment by hemker** [comment]
how to reproduce? pressing ignore in the "installed" tab or the "updated" tab?

**Comment by psyscope** [comment]
Sorry in the update thread. To get a lot of apps to appear. Choose not to
exlcude system and disabled apps. After you scan start clicking ignore. How
many ignores do you get to before it force quits?

**Comment by hemker** [comment]
all of them: 26 without a crash. how many do you need to crash the app? is it possible to send a logcat output?

**Comment by psyscope** [comment]
Ignore doesn't crash. This is the issue with the version numbers. It
confuses build number with version number, but each build version is for a
different phone/resolution.

**Comment by hemker** [comment]
@psyscope well, I'm confused :D however, is this issue about the app crashing when pressing ignore to many times, or is it about version/build number complications?

**Comment by psyscope** [comment]
LoL you fixed the app crashing problem, now it's the version # issue :)

**Comment by hemker** [comment]
@psyscope could you confirm that your points are fixed atm?

**Comment by psyscope** [comment]
Only issue is the version numbers of the same version, but for
differnt resolutions. Some Google apps show up twice.
